### ISSUE TITLE
Internal Network without Domain

### ISSUE THREAD

**Issue by daNick73** [Vertumnus/garmin-ioBrokerVis#1]
Hi.

I am using ioBroker in a strictly internal network, no ports being exposed externally (so, I access ioBroker only via http://192.168.178.xxx:8081 when in my local network).

Do I understand it correctly that I wont be able to use this project, simply since I wont be able to get an acceptable certificate (Let's Encrypt wont issue a strictly internal certificate, but only a domain based one).

THX!

Regards
daNick

**Comment by mstiem** [comment]
[daNick73](https://github.com/daNick73) , yes you need a certificate. I actually did that and have a running https connection with self signed certificates in my network.   here is an good example how to do that: [link](https://www.section.io/engineering-education/how-to-get-ssl-https-for-localhost/)

I Imported the ca certificate to my notebook, pc and even on my iPhone. When I test the connection over my cellphone 
https://192.168.178.73:8087/get/0_userdata.0.garmin/?val&user=garmin&pass=mypasswd I can see the config file but I always get on my watch a -400. The connection is secure without any certificate warning on my phone.
what I'm doing wrong?
Is  the connect app not using the CA's provided by my phone? My chrome and safari are working fine with the installed CA

**Comment by Vertumnus** [comment]
You are right. Unfortunately, it is not possible to use my App with self-signed certificates on the watch. It's a restriction of the garmin device. You cannot install self-signed certificates on the watch itself and the watch connects directly via the https protocol to the configured URL. It uses the smartphone as connector to the network / internet more or less as access point, but not the certificates on it. The advantage of this concept is that already the connection from the watch to the smartphone is secured (encrypted) and the smartphone (i.e. an App / Malware on it) cannot do a man-in-the-middle attack.

I had the same experiences during development and testing. First in the simulator on my workstation all worked fine with my self-signed certificates and of course also the API calls to ioBroker via my smartphone (on both my self-signed certificates were installed). But the watch always shows the -400 error code.

So I decided to use a dynamic DNS, Let's Encrypt and port forwarding to establish the connection. I fear this is the only way to get it work. Otherwise garmin had to provide the possibility installing self-signed certificates.

**Comment by daNick73** [comment]
In case I forgot: thx for the marvelous work and the detailed response!

Armin Junge ***@***.***> schrieb am Mi. 9. Nov. 2022 um 00:12:

**Comment by mstiem** [comment]
Hello, I just wanted to confirm @Vertumnus and give some hints to other users how I have implemented the Szenario:

Start: I want to use the api but only in my local network. I don't want to expose the simple-api to the internet(yet).

1) register own domain 
2) generate subdomain like "raspberrypi.mydomain.de" and add an A-Record for your local IP
3) generate certificate with the help of letsencrypt:
```
sudo apt-get remove certbot
sudo apt-get install snapd
sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
```

Open Port 80 and do port forwarding so certbot can verify and work properly

```
rm -rf /opt/iobroker/iobroker-data/letsencrypt
sudo certbot certonly --config-dir  /opt/iobroker/iobroker-data/letsencrypt --standalone --agree-tos --preferred-challenges http -d raspberrypi.mydomain.de

```
EMAIL Adresse eingeben
Y Enter
Y Enter

sudo chmod -R 755 /opt/iobroker/iobroker-data/letsencrypt/
- configure  certificate in system settings:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/2210293/205499837-187e64e7-7994-40d2-9731-1bdaa91a25c1.png">
- use and configure certificate in instances for admin, simpe-api  ....whatever you want
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/2210293/205500094-1f9948bf-492a-4fc9-91d0-9773a926f028.png">


CronJob check: 
`systemctl list-timers`

4) (EXTRA) use own DNS e.g. Pihole and create dns record to point an url to  a local ip.
With that setup I'm not exposing by machine with the api to the internet but can use it at home.
